// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_PersonPerRoom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_PersonPerRoom));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081124549_Update_PersonPerRoom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
